// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace personal_finance_and_budget_tracker_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260902130831_SaltHashPasswordSeederValues")]
    partial class SaltHashPasswordSeederValues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            Name = "Baby",
                            Type = "gelir"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Music",
                            Type = "gider"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Games",
                            Type = "gelir"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Clothing",
                            Type = "gider"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Games",
                            Type = "gider"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Computers",
                            Type = "gelir"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Beauty",
                            Type = "gelir"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Tools",
                            Type = "gelir"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Beauty",
                            Type = "gelir"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Jewelery",
                            Type = "gider"
                        });
                });

            modelBuilder.Entity("Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "Alpsalci.Atan@hotmail.com",
                            PasswordHash = "$2a$11$e8S.s/Hw.NnU1yZk5fJp2eZS1xJSsk8ERtvmPyhUkYZrEi9LYzOYi"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "Bulus76@gmail.com",
                            PasswordHash = "$2a$11$e8S.s/Hw.NnU1yZk5fJp2eZS1xJSsk8ERtvmPyhUkYZrEi9LYzOYi"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "Atalan38@gmail.com",
                            PasswordHash = "$2a$11$e8S.s/Hw.NnU1yZk5fJp2eZS1xJSsk8ERtvmPyhUkYZrEi9LYzOYi"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "Baysungur_Akal39@gmail.com",
                            PasswordHash = "$2a$11$e8S.s/Hw.NnU1yZk5fJp2eZS1xJSsk8ERtvmPyhUkYZrEi9LYzOYi"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "Aladag_Sayginer4@gmail.com",
                            PasswordHash = "$2a$11$e8S.s/Hw.NnU1yZk5fJp2eZS1xJSsk8ERtvmPyhUkYZrEi9LYzOYi"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "Alptutuk_Catalbas18@hotmail.com",
                            PasswordHash = "$2a$11$e8S.s/Hw.NnU1yZk5fJp2eZS1xJSsk8ERtvmPyhUkYZrEi9LYzOYi"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "Aydogan.Koyluoglu53@gmail.com",
                            PasswordHash = "$2a$11$e8S.s/Hw.NnU1yZk5fJp2eZS1xJSsk8ERtvmPyhUkYZrEi9LYzOYi"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "Buyat2@hotmail.com",
                            PasswordHash = "$2a$11$e8S.s/Hw.NnU1yZk5fJp2eZS1xJSsk8ERtvmPyhUkYZrEi9LYzOYi"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "Burkek24@gmail.com",
                            PasswordHash = "$2a$11$e8S.s/Hw.NnU1yZk5fJp2eZS1xJSsk8ERtvmPyhUkYZrEi9LYzOYi"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "Avsar4@hotmail.com",
                            PasswordHash = "$2a$11$e8S.s/Hw.NnU1yZk5fJp2eZS1xJSsk8ERtvmPyhUkYZrEi9LYzOYi"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
