// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace personal_finance_and_budget_tracker_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260902133915_RelationshipsAdded")]
    partial class RelationshipsAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            Name = "Baby",
                            Type = "gelir",
                            UserId = 13
                        },
                        new
                        {
                            Id = 11,
                            Name = "Beauty",
                            Type = "gelir",
                            UserId = 17
                        },
                        new
                        {
                            Id = 12,
                            Name = "Clothing",
                            Type = "gider",
                            UserId = 15
                        },
                        new
                        {
                            Id = 13,
                            Name = "Shoes",
                            Type = "gelir",
                            UserId = 17
                        },
                        new
                        {
                            Id = 14,
                            Name = "Beauty",
                            Type = "gelir",
                            UserId = 21
                        },
                        new
                        {
                            Id = 15,
                            Name = "Computers",
                            Type = "gider",
                            UserId = 11
                        },
                        new
                        {
                            Id = 16,
                            Name = "Jewelery",
                            Type = "gider",
                            UserId = 21
                        },
                        new
                        {
                            Id = 17,
                            Name = "Games",
                            Type = "gelir",
                            UserId = 31
                        },
                        new
                        {
                            Id = 18,
                            Name = "Jewelery",
                            Type = "gider",
                            UserId = 11
                        },
                        new
                        {
                            Id = 19,
                            Name = "Clothing",
                            Type = "gelir",
                            UserId = 37
                        },
                        new
                        {
                            Id = 20,
                            Name = "Clothing",
                            Type = "gider",
                            UserId = 15
                        },
                        new
                        {
                            Id = 21,
                            Name = "Books",
                            Type = "gelir",
                            UserId = 27
                        },
                        new
                        {
                            Id = 22,
                            Name = "Sports",
                            Type = "gelir",
                            UserId = 26
                        },
                        new
                        {
                            Id = 23,
                            Name = "Jewelery",
                            Type = "gider",
                            UserId = 21
                        },
                        new
                        {
                            Id = 24,
                            Name = "Games",
                            Type = "gelir",
                            UserId = 11
                        },
                        new
                        {
                            Id = 25,
                            Name = "Jewelery",
                            Type = "gider",
                            UserId = 13
                        },
                        new
                        {
                            Id = 26,
                            Name = "Computers",
                            Type = "gider",
                            UserId = 18
                        },
                        new
                        {
                            Id = 27,
                            Name = "Baby",
                            Type = "gelir",
                            UserId = 11
                        },
                        new
                        {
                            Id = 28,
                            Name = "Kids",
                            Type = "gider",
                            UserId = 11
                        },
                        new
                        {
                            Id = 29,
                            Name = "Grocery",
                            Type = "gider",
                            UserId = 28
                        },
                        new
                        {
                            Id = 30,
                            Name = "Electronics",
                            Type = "gelir",
                            UserId = 20
                        },
                        new
                        {
                            Id = 31,
                            Name = "Computers",
                            Type = "gelir",
                            UserId = 31
                        },
                        new
                        {
                            Id = 32,
                            Name = "Movies",
                            Type = "gelir",
                            UserId = 10
                        },
                        new
                        {
                            Id = 33,
                            Name = "Jewelery",
                            Type = "gelir",
                            UserId = 25
                        },
                        new
                        {
                            Id = 34,
                            Name = "Health",
                            Type = "gelir",
                            UserId = 34
                        },
                        new
                        {
                            Id = 35,
                            Name = "Books",
                            Type = "gelir",
                            UserId = 11
                        },
                        new
                        {
                            Id = 36,
                            Name = "Baby",
                            Type = "gelir",
                            UserId = 37
                        },
                        new
                        {
                            Id = 37,
                            Name = "Automotive",
                            Type = "gelir",
                            UserId = 21
                        },
                        new
                        {
                            Id = 38,
                            Name = "Kids",
                            Type = "gelir",
                            UserId = 21
                        },
                        new
                        {
                            Id = 39,
                            Name = "Games",
                            Type = "gelir",
                            UserId = 33
                        },
                        new
                        {
                            Id = 40,
                            Name = "Beauty",
                            Type = "gelir",
                            UserId = 18
                        },
                        new
                        {
                            Id = 41,
                            Name = "Outdoors",
                            Type = "gider",
                            UserId = 32
                        },
                        new
                        {
                            Id = 42,
                            Name = "Books",
                            Type = "gider",
                            UserId = 38
                        },
                        new
                        {
                            Id = 43,
                            Name = "Garden",
                            Type = "gider",
                            UserId = 14
                        },
                        new
                        {
                            Id = 44,
                            Name = "Music",
                            Type = "gelir",
                            UserId = 19
                        },
                        new
                        {
                            Id = 45,
                            Name = "Jewelery",
                            Type = "gelir",
                            UserId = 14
                        },
                        new
                        {
                            Id = 46,
                            Name = "Electronics",
                            Type = "gider",
                            UserId = 25
                        },
                        new
                        {
                            Id = 47,
                            Name = "Industrial",
                            Type = "gider",
                            UserId = 30
                        },
                        new
                        {
                            Id = 48,
                            Name = "Clothing",
                            Type = "gelir",
                            UserId = 26
                        },
                        new
                        {
                            Id = 49,
                            Name = "Industrial",
                            Type = "gider",
                            UserId = 10
                        },
                        new
                        {
                            Id = 50,
                            Name = "Garden",
                            Type = "gider",
                            UserId = 10
                        },
                        new
                        {
                            Id = 51,
                            Name = "Electronics",
                            Type = "gelir",
                            UserId = 11
                        },
                        new
                        {
                            Id = 52,
                            Name = "Electronics",
                            Type = "gider",
                            UserId = 22
                        },
                        new
                        {
                            Id = 53,
                            Name = "Music",
                            Type = "gider",
                            UserId = 13
                        },
                        new
                        {
                            Id = 54,
                            Name = "Music",
                            Type = "gelir",
                            UserId = 19
                        },
                        new
                        {
                            Id = 55,
                            Name = "Shoes",
                            Type = "gider",
                            UserId = 10
                        },
                        new
                        {
                            Id = 56,
                            Name = "Books",
                            Type = "gider",
                            UserId = 36
                        },
                        new
                        {
                            Id = 57,
                            Name = "Computers",
                            Type = "gider",
                            UserId = 35
                        },
                        new
                        {
                            Id = 58,
                            Name = "Home",
                            Type = "gider",
                            UserId = 29
                        },
                        new
                        {
                            Id = 59,
                            Name = "Kids",
                            Type = "gelir",
                            UserId = 18
                        });
                });

            modelBuilder.Entity("Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "Alpsalci.Atan@hotmail.com",
                            PasswordHash = "$2a$11$e8S.s/Hw.NnU1yZk5fJp2eZS1xJSsk8ERtvmPyhUkYZrEi9LYzOYi"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "Bulus76@gmail.com",
                            PasswordHash = "$2a$11$e8S.s/Hw.NnU1yZk5fJp2eZS1xJSsk8ERtvmPyhUkYZrEi9LYzOYi"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "Atalan38@gmail.com",
                            PasswordHash = "$2a$11$e8S.s/Hw.NnU1yZk5fJp2eZS1xJSsk8ERtvmPyhUkYZrEi9LYzOYi"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "Baysungur_Akal39@gmail.com",
                            PasswordHash = "$2a$11$e8S.s/Hw.NnU1yZk5fJp2eZS1xJSsk8ERtvmPyhUkYZrEi9LYzOYi"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "Aladag_Sayginer4@gmail.com",
                            PasswordHash = "$2a$11$e8S.s/Hw.NnU1yZk5fJp2eZS1xJSsk8ERtvmPyhUkYZrEi9LYzOYi"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "Alptutuk_Catalbas18@hotmail.com",
                            PasswordHash = "$2a$11$e8S.s/Hw.NnU1yZk5fJp2eZS1xJSsk8ERtvmPyhUkYZrEi9LYzOYi"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "Aydogan.Koyluoglu53@gmail.com",
                            PasswordHash = "$2a$11$e8S.s/Hw.NnU1yZk5fJp2eZS1xJSsk8ERtvmPyhUkYZrEi9LYzOYi"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "Buyat2@hotmail.com",
                            PasswordHash = "$2a$11$e8S.s/Hw.NnU1yZk5fJp2eZS1xJSsk8ERtvmPyhUkYZrEi9LYzOYi"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "Burkek24@gmail.com",
                            PasswordHash = "$2a$11$e8S.s/Hw.NnU1yZk5fJp2eZS1xJSsk8ERtvmPyhUkYZrEi9LYzOYi"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "Avsar4@hotmail.com",
                            PasswordHash = "$2a$11$e8S.s/Hw.NnU1yZk5fJp2eZS1xJSsk8ERtvmPyhUkYZrEi9LYzOYi"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "Bayruk_Akaydin@yahoo.com",
                            PasswordHash = "$2a$11$e8S.s/Hw.NnU1yZk5fJp2eZS1xJSsk8ERtvmPyhUkYZrEi9LYzOYi"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "Arsal.Aclan@yahoo.com",
                            PasswordHash = "$2a$11$e8S.s/Hw.NnU1yZk5fJp2eZS1xJSsk8ERtvmPyhUkYZrEi9LYzOYi"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "Bulmaz.Akman@gmail.com",
                            PasswordHash = "$2a$11$e8S.s/Hw.NnU1yZk5fJp2eZS1xJSsk8ERtvmPyhUkYZrEi9LYzOYi"
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "Barskan.Koyuncu@hotmail.com",
                            PasswordHash = "$2a$11$e8S.s/Hw.NnU1yZk5fJp2eZS1xJSsk8ERtvmPyhUkYZrEi9LYzOYi"
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "Abluc65@hotmail.com",
                            PasswordHash = "$2a$11$e8S.s/Hw.NnU1yZk5fJp2eZS1xJSsk8ERtvmPyhUkYZrEi9LYzOYi"
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "Gunes.Cevik@gmail.com",
                            PasswordHash = "$2a$11$e8S.s/Hw.NnU1yZk5fJp2eZS1xJSsk8ERtvmPyhUkYZrEi9LYzOYi"
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "Agalak43@yahoo.com",
                            PasswordHash = "$2a$11$e8S.s/Hw.NnU1yZk5fJp2eZS1xJSsk8ERtvmPyhUkYZrEi9LYzOYi"
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "Beg90@hotmail.com",
                            PasswordHash = "$2a$11$e8S.s/Hw.NnU1yZk5fJp2eZS1xJSsk8ERtvmPyhUkYZrEi9LYzOYi"
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "Burulday_Adal33@yahoo.com",
                            PasswordHash = "$2a$11$e8S.s/Hw.NnU1yZk5fJp2eZS1xJSsk8ERtvmPyhUkYZrEi9LYzOYi"
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "Altinkagan.Alyanak@hotmail.com",
                            PasswordHash = "$2a$11$e8S.s/Hw.NnU1yZk5fJp2eZS1xJSsk8ERtvmPyhUkYZrEi9LYzOYi"
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "Alptutuk59@hotmail.com",
                            PasswordHash = "$2a$11$e8S.s/Hw.NnU1yZk5fJp2eZS1xJSsk8ERtvmPyhUkYZrEi9LYzOYi"
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "Kimizin_Tekand28@yahoo.com",
                            PasswordHash = "$2a$11$e8S.s/Hw.NnU1yZk5fJp2eZS1xJSsk8ERtvmPyhUkYZrEi9LYzOYi"
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "Kimizalmila34@yahoo.com",
                            PasswordHash = "$2a$11$e8S.s/Hw.NnU1yZk5fJp2eZS1xJSsk8ERtvmPyhUkYZrEi9LYzOYi"
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "Adberilgen3@hotmail.com",
                            PasswordHash = "$2a$11$e8S.s/Hw.NnU1yZk5fJp2eZS1xJSsk8ERtvmPyhUkYZrEi9LYzOYi"
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "Berkis99@gmail.com",
                            PasswordHash = "$2a$11$e8S.s/Hw.NnU1yZk5fJp2eZS1xJSsk8ERtvmPyhUkYZrEi9LYzOYi"
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "Alkaevli75@gmail.com",
                            PasswordHash = "$2a$11$e8S.s/Hw.NnU1yZk5fJp2eZS1xJSsk8ERtvmPyhUkYZrEi9LYzOYi"
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "Abay_Akar23@hotmail.com",
                            PasswordHash = "$2a$11$e8S.s/Hw.NnU1yZk5fJp2eZS1xJSsk8ERtvmPyhUkYZrEi9LYzOYi"
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "Edil_Dogan@hotmail.com",
                            PasswordHash = "$2a$11$e8S.s/Hw.NnU1yZk5fJp2eZS1xJSsk8ERtvmPyhUkYZrEi9LYzOYi"
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "Aral2@yahoo.com",
                            PasswordHash = "$2a$11$e8S.s/Hw.NnU1yZk5fJp2eZS1xJSsk8ERtvmPyhUkYZrEi9LYzOYi"
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "Isik.Ozkok88@gmail.com",
                            PasswordHash = "$2a$11$e8S.s/Hw.NnU1yZk5fJp2eZS1xJSsk8ERtvmPyhUkYZrEi9LYzOYi"
                        });
                });

            modelBuilder.Entity("Category", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany("Categories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Transaction", b =>
                {
                    b.HasOne("Category", "Category")
                        .WithMany("Transactions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Category", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
